language: bash
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y curl unzip python-pip npm
- sudo pip install mkdocs
- sudo npm install marked --global
install:
- bash ./download.sh
script:
- test $TRAVIS_PULL_REQUEST == "false" && echo "travis-ci don't support qiniu, so deploy manually" || exit 0
- bash ./before_upload.sh || exit 1
- export PATH=$PATH:$PWD/qiniu/
- bash ./upload.sh
- bash ./portal.fill.sh
- bash ./portal.build.sh
- bash ./portal.upload.sh
