language: bash
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y curl discount dnsutils coreutils unzip
install:
- bash ./download.sh
script:
- test $TRAVIS_PULL_REQUEST == "false" && echo "travis-ci don't support qiniu, so deploy manually" || exit 0
- wget -O /tmp/qiniu-devtools-linux_amd64-current.tar.gz http://devtools.qiniu.io/qiniu-devtools-linux_amd64-current.tar.gz || exit 1
- mkdir qiniu
- tar -zxvf /tmp/qiniu-devtools-linux_amd64-current.tar.gz -C ./qiniu/ || exit 2
- wget -O /tmp/qshell.zip http://qdisk.qiniudn.com/qshell%20v1.4.5.zip
- unzip /tmp/qshell.zip -d ./qiniu/ || exit 2
- cp ./qiniu/qshell_linux_amd64 ./qiniu/qshell
- export PATH=$PATH:$PWD/qiniu/
- sed -e "s|{access_key}|$qiniu_access_key|g" -e "s|{secret_key}|$qiniu_secret_key|g" -e "s|{src_dir}|$PWD/dl|g" -e "s|{key_prefix}||g" qshell.conf.tpl > qshell.conf
- bash ./upload.sh
