# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # TODO hard code, because GitHub Actions only support secrets but not env
    env:
      CODING_GENERIC_REGISTRY: https://coding-public-generic.pkg.coding.net/public/downloads/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Lint
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          apt-get update
          apt-get install -y shellcheck
          wget https://github.com/mvdan/sh/releases/download/v3.3.1/shfmt_v3.3.1_linux_amd64 -O /usr/local/bin/shfmt
          chmod +x /usr/local/bin/shfmt
          git diff --diff-filter=d --name-only origin/$GITHUB_BASE_REF... | xargs ./lint.sh

      # Download and check sha256, if file not exist in registry
      - name: Download and check
        run: ./coding-generic-sync.sh

